

default:
  rails_cache_store: <%= ENV.fetch('RAILS_CACHE_STORE') { :memcache }.to_sym %>
  session_store: <%= ENV.fetch('SESSION_STORE') { :active_record_store }.to_sym %>
  email_delivery_method: <%= ENV.fetch('EMAIL_DELIVERY_METHOD') { :sendmail } %>
  smtp_address: <%= ENV['SMTP_HOST'] %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 25 }.to_i %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { ENV['HOSTNAME'] } %>
  smtp_authentication: <%= ENV.fetch('SMTP_AUTHENTICATION') { :login }.to_sym %>
  smtp_user_name: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_enable_starttls_auto: <%= ENV.fetch('SMTP_ENABLE_STARTTLS_AUTO') { "false" } %>
  smtp_ssl: <%= ENV.fetch('SMTP_SSL') { "false" } %>
  attachments_storage_path: <%= ENV.fetch('ATTACHMENTS_STORAGE_PATH') { "/var/db/_APP_NAME_/files" } %>
<% git_configured = ENV['GIT_REPOSITORIES'].present? %>
<% svn_configured = ENV['SVN_REPOSITORIES'].present? %>
<% if git_configured || svn_configured %>
  scm:
  <% if git_configured %>
    git:
      manages: <%= ENV['GIT_REPOSITORIES'] %>
      mode: 0770
      group: <%= ENV['SERVER_GROUP'] %>
  <% end %>
  <% if svn_configured %>
    subversion:
      # SVN uses Apache repository wrapper due to permission errors in multi-user operation
      manages: <%= ENV['SVN_REPOMAN_URL'] %>
      # Do noot verify SSL certificates when SERVER_PROTOCOL is 'https'.
      # As we currently only support local repoman installations with packager,
      # this option is set to true by default.
      insecure: true
      access_token: <%= ENV['SVN_REPOMAN_TOKEN'] %>
  <% end %>
<% end %>
