#!/bin/bash
set -e

[ -f /etc/apache2/sites-enabled/proyeksiapp.conf ] || erb -r time $APP_PATH/docker/prod/proxy.conf.erb > /etc/apache2/sites-enabled/proyeksiapp.conf
exec /usr/sbin/apache2ctl -DFOREGROUND
